### ISSUE TITLE
Broken jobs because of Jenkins Bug.

### ISSUE THREAD

**Issue by pointwisefixed** [oneops/build-wf#6]
Right now if you do a clean checkout of this project, it will not build any of the projects due to this jenkins bug https://issues.jenkins-ci.org/browse/JENKINS-34181. You have to update the aforementioned plugin so it works correctly (or you can change the configs.xml to account for that). This is kind of an annoying issue because this transitively makes the setup project fail too.

**Comment by pointwisefixed** [comment]
Created a PR to resolve this until the plugin update is propagated to central

**Comment by sureshg** [comment]
PR fixed the vagrant build. Closing this issue.
